# Generated by Django 4.2 on 2023-05-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Book title')),
                ('author', models.CharField(max_length=200, verbose_name='Book author')),
                ('date_released', models.DateTimeField(auto_now_add=True)),
                ('plan', models.CharField(choices=[('level_1', 'Free'), ('level_2', 'Advanced'), ('level_3', 'Pro'), ('level_4', 'Premium')], max_length=7, verbose_name='Plan')),
            ],
        ),
    ]
